### ISSUE TITLE
TuneFormat does not exist on rust-mavlink

### ISSUE THREAD

**Issue by patrickelectric** [mavlink/rust-mavlink#120]
https://mavlink.io/en/messages/common.html#TUNE_FORMAT

**Comment by Erk-** [comment]
This will be there if the `mavlink` submodule is updated:
![image](https://user-images.githubusercontent.com/3659684/185947113-653008c4-5ffc-4715-92f9-a86a3e70321d.png)

**Comment by patrickelectric** [comment]
> This will be there if the `mavlink` submodule is updated: ![image](https://user-images.githubusercontent.com/3659684/185947113-653008c4-5ffc-4715-92f9-a86a3e70321d.png)

master branch of rust-mavlink does not build with the latest version of the mavlink repository. 

can you specify the mavlink hash that builds and contains tune format ?

**Comment by patrickelectric** [comment]
Well, it appears that is showing now, closing it.
