### ISSUE TITLE
Getting ready for an official release

### ISSUE THREAD

**Issue by podhrmic** [mavlink/rust-mavlink#14]
This is a tracking issue to make rust-mavlink an officially supported Mavlink implementation.

What needs to happen?

- [x] Split messages into one file per message (similar to what mavgen does)
- [x] Add quickcheck tests for each message
- [x] change enums to uints
- [x] Add fuzz testing
- [ ] (optional) Build actual enums on top of message enums
- [ ] Mavlink 2 support, including signing
- [x] Quote update
- [x] Somehow ensure max vector length for messages like v2_extension and statustext
- [ ] Support for other dialects

**Comment by podhrmic** [comment]
FYI work in progress, check out https://github.com/GaloisInc/rust-mavlink/tree/fuzz_testing for the latest commits

**Comment by podhrmic** [comment]
Added fuzz testing, and started adding quickcheck tests.

Next steps:
- figure out how to implement `Arbitrary` for `ArrayVec`
- implement `Arbitrary` for `MavMessage` and `MavFrame` to complete quickcheck tests

@hamishwillee do you think we need to have hardcoded test vectors as well? Or is a random (quickcheck) testing considered sufficient? Meaning - I generate a message (let's say `HEARTBEAT`) with random values and try to serialize and then deserialize it?

**Comment by hamishwillee** [comment]
@podhrmic Sorry for the delay, I'm travelling.

> do you think we need to have hardcoded test vectors as well? Or is a random (quickcheck) testing considered sufficient? Meaning - I generate a message (let's say HEARTBEAT) with random values and try to serialize and then deserialize it?

Short version ... no.

Generally the steer from @peterbarker on the mavgen library has been "try to test to the same level as the other libraries" - ie C. I believe the C library tests every message but I don't know what values are passed in - ie whether they are random or not. 
My gut feeling is that random is good, but we may need to tune this to avoid false positives for some messages. 

What we _should_ do is work out a minimum test strategy for any generator library and document it - so you don't have to ask these questions. Also once we know what is tested, do a gap analysis to see if the coverage is reasonable. @peterbarker Do you have a summary anywhere of what tests are run for pymavlink and the C libraries?

**Comment by podhrmic** [comment]
Thanks @hamishwillee for the update. 

FYI updates on my side if you are interested:
- switching to use `ArrayVec` only for arrays > 32 elements, otherwise will use slices
- working on generating enums as defined in the XML (for easier typechecking) that allow unknown values

**Comment by podhrmic** [comment]
Closing as this is not relevant anymore. Some of the ideas (fuzz testing, etc) can be incorporated later if needed.
