### ISSUE TITLE
Can this library serve as vehicle?

### ISSUE THREAD

**Issue by wucke13** [mavlink/rust-mavlink#15]
Skimming the docs, I only read about possibilities of connecting to a given network resource (hostname/ip + port). Can this library also be used to bind a TCP server locally, so that other non vehicle nodes (like GCS) can connect to to it (so that one may use this library on a vehicle)?

**Comment by kevinmehall** [comment]
`tcpin` listens on a socket for incoming connections. The address is the bind address -- use `127.0.0.1` for localhost-only, or `0.0.0.0` to listen on all interfaces.

**Comment by wucke13** [comment]
@kevinmehall Thanks for the fast response :)
