### ISSUE TITLE
0.12.2 does not compile

### ISSUE THREAD

**Issue by gwbres** [mavlink/rust-mavlink#212]
Hello,

I'm interested in building custom Mavlink protos. Therefore I download and try to build the simplest form of this repository:

```bash
cargo build --features common
```

But this fails due to errors in the generated code related to Bitflags types.  
It complains bitflags can only be bumped using `BitFlags::to_bits()`, not `as u32`:

![image](https://github.com/mavlink/rust-mavlink/assets/7270467/86d82891-f651-4938-a011-e589a9bfc91a)

And the mirror operation :

![image](https://github.com/mavlink/rust-mavlink/assets/7270467/d8ba223d-ef65-4bbf-8d02-18c224507b51)

A bitflag is not a primitive type. It should be built with `BitFlags::from_bits(u32)`

It seems that your build script already contains an attempt at dealing with those cases:

![image](https://github.com/mavlink/rust-mavlink/assets/7270467/21342edb-b562-4c5a-b0f4-e199adf49001)

but for some reason we windup in the other branch. Unfortunately this is very cryptic to me and am unable to provide help.

* Am I missing something when building your library ?
* obviously 0.12.0 was released for a reason, why am I unable to build this "simple" form ?
* I'm also surprized I can't seem to get rid of the `uavionix` protocol, event when I only activate the `common` feature.
Let's keep in mind I'm interested in building my custom protocol only, therefore I foresee only including the basics and my protocol, not interested in any other. There is some kind of black magic adding this one whatever happens.

**Comment by patrickelectric** [comment]
Hi @gwbres,

I would recommend to update your rust version with `rustup update` and `rustup override set stable`. To test I did build it with stable and nightly as well.

![image](https://github.com/mavlink/rust-mavlink/assets/1215497/8d9951f0-6b5a-42e6-9eeb-1050683f0b2f)


Try also a cargo clean and a cargo update just to be sure.
You can also check the steps on our ci that it's also passing with all tests.
How did you check for uavionix ? Only common should be integrated if you choose such feature.

**Comment by gwbres** [comment]
@patrickelectric, 

first of all, thank you for your support ! 
I confirm that after a cargo clean, rustup update & rebuild it did pass.  
It was either a git cache or a cargo cache "issue", but that is not clear to me.

**Comment by gwbres** [comment]
@patrickelectric, 

first of all, thank you for your support ! 
I confirm that after a cargo clean, rustup update & rebuild it did pass.  
It was either a git cache or a cargo cache "issue", but that is not clear to me.
