### ISSUE TITLE
0.13.0 not published on crates.io

### ISSUE THREAD

**Issue by JoeHut** [mavlink/rust-mavlink#226]
Hey!
Is there a reason the latest release 0.13.0 is not released on crates.io yet? I would love to use the code generation!
https://crates.io/crates/mavlink/versions

**Comment by patrickelectric** [comment]
Hi @JoeHut I'll take a look

**Comment by patrickelectric** [comment]
It appears that the new struct using multiple projects and path as dependency is breaking rust-mavlink release.
@GrahamDennis can you give a hand on that ?

**Comment by BKSalman** [comment]
maybe because versions were not updated in [mavlink](https://github.com/mavlink/rust-mavlink/blob/1208960092e6fd942d240d67670f6dc9cb3eb73b/mavlink/Cargo.toml#L4) and [mavlink-core](https://github.com/mavlink/rust-mavlink/blob/1208960092e6fd942d240d67670f6dc9cb3eb73b/mavlink-core/Cargo.toml#L3)

**Comment by qwerty19106** [comment]
Any updates for it?

**Comment by patrickelectric** [comment]
Fixed
