### ISSUE TITLE
Test with no-dev-deps all-targets

### ISSUE THREAD

**Issue by pv42** [mavlink/rust-mavlink#277]
The MSRV check tests run
`cargo no-dev-deps check --all --all-targets [features]`
this appears to me as a mistake since no-dev-deps disables dev dependencies but --all-targets includes test which (might) need dev dependencies.
This was changed recently by @danieleades in a729400 so I was wondering if there is a reason for it that I am missing or if is just a mistake. If so it can by fixed by changing the check to either `cargo check --all --all-targets [features]` or split commands for targets that need dev-deps:
- `cargo no-dev-deps check --all --lib --bins [features]`
- `cargo check --all --tests --benches --examples [features]`

**Comment by danieleades** [comment]
Yeah I suspect `--all-targets` can be removed
