### ISSUE TITLE
Create a new release with the last version of master branch

### ISSUE THREAD

**Issue by patrickelectric** [mavlink/rust-mavlink#29]
It would be awesome to have a new release with our last corrections and new message definitions :)

**Comment by patrickelectric** [comment]
@tstellanova ping.
I did a camera manager with rtsp and mavlink using rust, but for that it's necessary a new release to do the deploy via cargo.
https://github.com/patrickelectric/ardupilot-camera-manager

**Comment by patrickelectric** [comment]
ping @podhrmic

**Comment by michael-p** [comment]
Please see #24 first, seems there are some problems with the new messages.
