### ISSUE TITLE
A new release before multiple messages definitions 

### ISSUE THREAD

**Issue by patrickelectric** [mavlink/rust-mavlink#33]
Right now we have the full common message definition available.
It's a good time to do a new release before the multiple message definition integration [ardupilotmega, autoquad, minimal, standard, ...].

**Comment by patrickelectric** [comment]
ping @podhrmic

**Comment by podhrmic** [comment]
I can push to crates.io (I *think* I have access)
@patrickelectric do you want to make any additional changes in the documentation/etc. before pushing the new release?

**Comment by patrickelectric** [comment]
@podhrmic I did some small improvements and updates in Cargo to 0.7 release,
you can check it here: https://github.com/mavlink/rust-mavlink/pull/34

**Comment by podhrmic** [comment]
@patrickelectric I don't have access rights to the [mavlink crate](https://crates.io/crates/mavlink) 

@tstellanova @mrpollo @kevinmehall @tcr3dr can you please add me as an owner? (or publish the new version yourself)

**Comment by patrickelectric** [comment]
@podhrmic We could also do such thing via travis, if someone could setup the token.

**Comment by tstellanova** [comment]
Sent you an invite Michal— let me know if I need to do more.

**Comment by podhrmic** [comment]
Done! https://crates.io/crates/mavlink

**Comment by patrickelectric** [comment]
![f6b293cd521fc13f3c7f0d0aefeafdc3](https://user-images.githubusercontent.com/1215497/73591514-30267580-44ce-11ea-9d64-45cbd0596f97.jpg)
