### ISSUE TITLE
Force update 0.8.3 tag to deploy version 

### ISSUE THREAD

**Issue by patrickelectric** [mavlink/rust-mavlink#56]
@podhrmic since travis failed with the test and was unable to release 0.8.3 in rust crates, I believe that we should force push the tag to the current master branch

**Comment by podhrmic** [comment]
I had to verify an email on crates.io to get it work, silly. 
We have 0.8.3 now! https://crates.io/crates/mavlink
Thanks for all the work @patrickelectric !

**Comment by patrickelectric** [comment]
Thank you for your time @podhrmic
