### ISSUE TITLE
cargo token need to be updated

### ISSUE THREAD

**Issue by patrickelectric** [mavlink/rust-mavlink#75]
@podhrmic can you update the token in our travis configuration ? Right now it's not impossible to do new releases:

> error: api errors (status 401 Unauthorized): The given API token does not match the format used by crates.io. Tokens generated before 2020-07-14 were generated with an insecure random number generator, and have been revoked. You can generate a new token at https://crates.io/me. For more information please see https://blog.rust-lang.org/2020/07/14/crates-io-security-advisory.html. We apologize for any inconvenience.

**Comment by podhrmic** [comment]
Fixed with dc912494fca678b96a68c61c035dba92a49879de
